@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< Updated upstream
REM Generated by Vivado on Thu Feb 27 21:04:35 -0600 2025
=======
REM Generated by Vivado on Tue Mar 04 22:05:47 -0600 2025
>>>>>>> Stashed changes
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
<<<<<<< Updated upstream
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot four_bit_RCA_tb_behav xil_defaultlib.four_bit_RCA_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot four_bit_RCA_tb_behav xil_defaultlib.four_bit_RCA_tb xil_defaultlib.glbl -log elaborate.log
=======
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot CLA32_tb_behav xil_defaultlib.CLA32_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot CLA32_tb_behav xil_defaultlib.CLA32_tb xil_defaultlib.glbl -log elaborate.log
>>>>>>> Stashed changes
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
