@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< Updated upstream
REM Generated by Vivado on Thu Feb 27 21:04:37 -0600 2025
=======
REM Generated by Vivado on Tue Mar 04 21:58:17 -0600 2025
>>>>>>> Stashed changes
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
<<<<<<< Updated upstream
echo "xsim four_bit_RCA_tb_behav -key {Behavioral:sim_1:Functional:four_bit_RCA_tb} -tclbatch four_bit_RCA_tb.tcl -log simulate.log"
call xsim  four_bit_RCA_tb_behav -key {Behavioral:sim_1:Functional:four_bit_RCA_tb} -tclbatch four_bit_RCA_tb.tcl -log simulate.log
=======
echo "xsim CLA32_tb_behav -key {Behavioral:sim_1:Functional:CLA32_tb} -tclbatch CLA32_tb.tcl -log simulate.log"
call xsim  CLA32_tb_behav -key {Behavioral:sim_1:Functional:CLA32_tb} -tclbatch CLA32_tb.tcl -log simulate.log
>>>>>>> Stashed changes
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
